baseURL = "https://teamrelectric.ca"
languageCode = "en-us"
title = "Relectric Car Team"
theme = "kross"
summaryLength = "10"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"


# navigation
[menu]

  [[menu.main]]
  name="Home"
  URL=""
  weight=1

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.main]]
  name = "Team"
  url = "team"
  weight = 3

  [[menu.main]]
  name = "Sponsors"
  URL = "sponsors"
  weight = 4

  [[menu.main]]
  name = "Gallery"
  URL = "gallery"
  weight = 5

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 6


[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Relectric Car Team"
# Google Analitycs
googleAnalitycsID = "Your ID"
debug = true

  # Preloader
  [params.preloader]
  enable = true

  [params.contact]
  enable = true
  formAction = "https://formspree.io/mwkvwrlg" #contact form works with formspree.io

  [params.footer]
  email = "info@teamrelectric.ca"
  address = "622 Collegiate Pl NW, Calgary, AB T2N 4V8"
